# Designed for guition-esp32-p4-jc4880p443
substitutions:
  name: "your-device-name"
  friendly_name: "Your Room Sensor"
  room: "Your Room"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  post_connect_roaming: false

# Packages
packages:
  setup:
    url: https://github.com/jtenniswood/esphome-lvgl/
    file: guition-esp32-p4-jc4880p443/package.yaml
    refresh: 1sec
