# ESP32-S3-Touch-LCD-7
substitutions:
  name: "your-device-name"
  friendly_name: "Your Room Sensor"
  room: "Your Room"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  setup:
    url: https://github.com/jtenniswood/esphome-lvgl/
    files: [guition-esp32-p4-jc1060p470/device/device.yaml,
            guition-esp32-p4-jc1060p470/device/sensors.yaml,
            guition-esp32-p4-jc1060p470/device/lvgl.yaml,
            guition-esp32-p4-jc1060p470/addon/time.yaml,
            guition-esp32-p4-jc1060p470/addon/backlight.yaml,
            guition-esp32-p4-jc1060p470/addon/network.yaml,
            guition-esp32-p4-jc1060p470/assets/fonts.yaml,
            guition-esp32-p4-jc1060p470/assets/icons.yaml,
            guition-esp32-p4-jc1060p470/theme/button.yaml]
    refresh: 1sec
