# ESP32-P4-JC4880P443
substitutions:
  name: "your-device-name"
  friendly_name: "Your Room Sensor"
  room: "Your Room"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  post_connect_roaming: false

# Packages
packages:
  setup:
    url: https://github.com/jtenniswood/esphome-lvgl/
    files: [guition-esp32-p4-jc4880p443/device/device.yaml,
            guition-esp32-p4-jc4880p443/device/sensors.yaml,
            guition-esp32-p4-jc4880p443/device/lvgl.yaml,
            guition-esp32-p4-jc4880p443/addon/time.yaml,
            guition-esp32-p4-jc4880p443/addon/backlight.yaml,
            guition-esp32-p4-jc4880p443/addon/network.yaml,
            guition-esp32-p4-jc4880p443/assets/fonts.yaml,
            guition-esp32-p4-jc4880p443/assets/icons.yaml,
            guition-esp32-p4-jc4880p443/theme/button.yaml]
    refresh: 1sec
